/**
 * Authorization
 */
export const AUTH_SESSION_WAITING = "AUTH_SESSION_WAITING";
export const AUTH_SESSION_SUCCESS = "AUTH_SESSION_SUCCESS";
export const AUTH_SESSION_FAILURE = "AUTH_SESSION_FAILURE";

export const AUTH_LOGIN_WAITING = "AUTH_LOGIN_WAITING";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";

export const AUTH_LOGOUT_WAITING = "AUTH_LOGOUT_WAITING";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_FAILURE = "AUTH_LOGOUT_FAILURE";

export const AUTH_REGISTER_WAITING = "AUTH_REGISTER_WAITING";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";

export const AUTH_PASSWORD_CHECK_WAITING = "AUTH_PASSWORD_CHECK_WAITING";
export const AUTH_PASSWORD_CHECK_SUCCESS = "AUTH_PASSWORD_CHECK_SUCCESS";
export const AUTH_PASSWORD_CHECK_FAILURE = "AUTH_PASSWORD_CHECK_FAILURE";


/**
 * UserState
 */
export const USERSTATE_UPDATE_WAITING = "USERSTATE_UPDATE_WAITING";
export const USERSTATE_UPDATE_SUCCESS = "USERSTATE_UPDATE_SUCCESS";
export const USERSTATE_UPDATE_FAILURE = "USERSTATE_UPDATE_FAILURE";

export const USERSTATE_DELETE_WAITING = "USERSTATE_DELETE_WAITING";
export const USERSTATE_DELETE_SUCCESS = "USERSTATE_DELETE_SUCCESS";
export const USERSTATE_DELETE_FAILURE = "USERSTATE_DELETE_FAILURE";


/**
 * Algorithm
 */
export const GET_ALGORITHM_LIST_WAITING = "GET_ALGORITHM_LIST_WAITING";
export const GET_ALGORITHM_LIST_FAILURE = "GET_ALGORITHM_LIST_FAILURE";
export const GET_ALGORITHM_LIST_SUCCESS = "GET_ALGORITHM_LIST_SUCCESS";

export const GET_ALGORITHM_DATA_WAITING = "GET_ALGORITHM_DATA_WAITING";
export const GET_ALGORITHM_DATA_FAILURE = "GET_ALGORITHM_DATA_FAILURE";
export const GET_ALGORITHM_DATA_SUCCESS = "GET_ALGORITHM_DATA_SUCCESS";


/**
 * Question
 */
export const GET_QUESTION_STATE_WAITING = "GET_QUESTION_STATE_WAITING";
export const GET_QUESTION_STATE_SUCCESS = "GET_QUESTION_STATE_SUCCESS";
export const GET_QUESTION_STATE_FAILURE = "GET_QUESTION_STATE_FAILURE";


/**
 * User-Report
 */
 export const POST_USER_REOPRT_WAITING = "POST_USER_REOPRT_WAITING";
 export const POST_USER_REOPRT_SUCCESS = "POST_USER_REOPRT_SUCCESS";
 export const POST_USER_REOPRT_FAILURE = "POST_USER_REOPRT_FAILURE";


 /**
  * Admin-Notice
  */
  export const GET_NOTICE_WAITING = "GET_NOTICE_WAITING";
  export const GET_NOTICE_SUCCESS = "GET_NOTICE_SUCCESS";
  export const GET_NOTICE_FAILURE = "GET_NOTICE_FAILURE";