/**
 * Authorization
 */
export const AUTH_SESSION_WAITING = "AUTH_SESSION_WAITING";
export const AUTH_SESSION_SUCCESS = "AUTH_SESSION_SUCCESS";
export const AUTH_SESSION_FAILURE = "AUTH_SESSION_FAILURE";

export const AUTH_LOGIN_WAITING = "AUTH_LOGIN_WAITING";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";

export const AUTH_LOGOUT_WAITING = "AUTH_LOGOUT_WAITING";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_FAILURE = "AUTH_LOGOUT_FAILURE";

export const AUTH_REGISTER_WAITING = "AUTH_REGISTER_WAITING";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";

/**
 * Algorithm
 */
export const GET_ALGORITHM_LIST = "GET_ALGORITHM_LIST";

export const GET_ALGORITHM_LIST_FAILURE = "GET_ALGORITHM_LIST_FAILURE";
export const GET_ALGORITHM_LIST_SUCCESS = "GET_ALGORITHM_LIST_SUCCESS";

export const GET_ALGORITHM_DATA = "GET_ALGORITHM_DATA";
export const GET_ALGORITHM_DATA_FAILURE = "GET_ALGORITHM_DATA_FAILURE";
export const GET_ALGORITHM_DATA_SUCCESS = "GET_ALGORITHM_DATA_SUCCESS";


