export const GET_ALGORITHM_LIST = "GET_ALGORITHM_LIST";

export const GET_ALGORITHM_LIST_FAILURE = "GET_ALGORITHM_LIST_FAILURE";
export const GET_ALGORITHM_LIST_SUCCESS = "GET_ALGORITHM_LIST_SUCCESS";

export const GET_ALGORITHM_DATA = "GET_ALGORITHM_DATA";
export const GET_ALGORITHM_DATA_FAILURE = "GET_ALGORITHM_DATA_FAILURE";
export const GET_ALGORITHM_DATA_SUCCESS = "GET_ALGORITHM_DATA_SUCCESS";



export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_WAITING = "AUTH_LOGIN_WAITING";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_WAITING = "AUTH_REGISTER_WAITING";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
